name: Lint and Test
on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: yarn

      - name: Install project dependencies
        run: yarn install

      - name: Run build script
        run: yarn build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Plasma
          path: |
            dist
            types

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: yarn

      - name: Install project dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: yarn

      - name: Fetch build artifacts
        uses: actions/download-artifact@v3
        with:
          name: Plasma

      - name: Run tests
        run: yarn test
